### ISSUE TITLE
multiblog not working

### ISSUE THREAD

**Issue by habnai** [hwdsl2/setup-ghost-blog#1]
can not setup other blog its freeze on first setup

**Comment by hwdsl2** [comment]
Hi @habnai Can you please elaborate at which step did it freeze? Did you see any error?

**Comment by habnai** [comment]
hi i test it locally and on vps  the initial blog everything ok but the second its freeze on ivite your team this error.log from nginx 
2016/04/30 21:37:57 [alert] 3396#0: *8 no upstream configuration, client:$on/setup/ HTTP/1.1", host: "blog2.com", referrer: "http://blog2/ghost/setup/two/"

**Comment by hwdsl2** [comment]
I plan to look into this issue when I have time. Thank you for your patience.

**Edit:** See my comment below for a workaround.

**Comment by habnai** [comment]
no problem i will test it thank you 
for this great work

**Comment by hwdsl2** [comment]
The error you encountered is due to a bug in ModSecurity [1] [2] which generates HTTP 500 "no upstream configuration" errors on POST requests, only in the case of multiple server blocks (or blogs).

At this time, please use the following workaround:   

Set up SSH port forwarding in your SSH client for port 2368 (first blog), 2369 (second blog), etc. Then browse to http://localhost:2368/ghost, http://localhost:2369/ghost, etc. to configure your blog(s).

[1] https://github.com/SpiderLabs/ModSecurity/issues/582#issuecomment-149437170
[2] https://github.com/SpiderLabs/ModSecurity/issues/664

**Comment by hwdsl2** [comment]
Closing this for now. A note had been added to the setup script regarding the above workaround.
