### ISSUE TITLE
 failed (13: Permission denied),

### ISSUE THREAD

**Issue by habnai** [hwdsl2/setup-ghost-blog#8]
hi
after a fresh install on centos 7 and debian 8 also with naxsi or with mode security,i get this error : /content/themes/casper/assets/js/index.js" failed (13: Permission denied),all js file get permission denied its fresh install with casper theme,this the logs nginx

```
2016/10/23 15:59:17 [error] 21281#0: *1 open() "content/themes/casper/assets/css/screen.css" failed (13: Permission denied), client: 
2016/10/23 15:59:17 [error] 21281#0: *1 open() "content/themes/casper/assets/js/jquery.fitvids.js" failed (13: Permission denied), client: 
2016/10/23 15:59:17 [error] 21281#0: *3 open() "content/themes/casper/assets/js/index.js" failed (13: Permission denied), client
2016/10/23 15:59:23 [error] 21281#0: *4 open() "content/themes/casper/assets/css/screen.css" failed (13: Permission denied), client
2016/10/23 15:59:23 [error] 21281#0: *5 open() "content/themes/casper/assets/js/jquery.fitvids.js" failed (13: Permission denied), client
2016/10/23 15:59:23 [error] 21281#0: *6 open() "content/themes/casper/assets/js/index.js" failed (13: Permission denied), client
```

**Comment by hwdsl2** [comment]
@habnai Hello! I looked into this and the error is caused by your `/var/www/BLOG_FULL_DOMAIN_NAME` folder having permission 700. Nginx runs as the `nginx` user and must have access to that folder in order to retrieve the theme files.

To fix this, run command (replace with actual value):

```
chmod 755 /var/www/BLOG_FULL_DOMAIN_NAME
```

I'll push a fix to the repo for this.
